# Generated by Django 4.1.6 on 2023-02-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_carousel_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='action_name',
        ),
    ]
