# Generated by Django 4.1.6 on 2023-02-24 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_carousel_action_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
