# Generated by Django 4.1.6 on 2023-02-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_product_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.TextField(blank=True),
        ),
    ]
