# Generated by Django 4.1.6 on 2023-05-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Дизайн', models.CharField(max_length=400)),
                ('Функционал', models.CharField(max_length=400)),
                ('Креативность', models.CharField(max_length=400)),
                ('Простота использования', models.CharField(max_length=400)),
                ('Наполнение', models.CharField(max_length=400)),
                ('Другое', models.CharField(max_length=400)),
            ],
        ),
    ]
