# Generated by Django 4.1.6 on 2023-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_pool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='Простота использования',
        ),
    ]
