# Generated by Django 4.1.6 on 2023-05-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_pool_простота использования'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='Дизайн',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='Другое',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='Креативность',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='Наполнение',
        ),
        migrations.RemoveField(
            model_name='pool',
            name='Функционал',
        ),
        migrations.AddField(
            model_name='pool',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Согласие на получение рассылки'),
        ),
        migrations.AddField(
            model_name='pool',
            name='content',
            field=models.CharField(choices=[('1', 'Отвратительно'), ('2', 'Плохо'), ('3', 'Нормально'), ('4', 'Отлично'), ('5', 'Восхитительно')], default='5', max_length=400),
        ),
        migrations.AddField(
            model_name='pool',
            name='creativity',
            field=models.CharField(choices=[('1', 'Отвратительно'), ('2', 'Плохо'), ('3', 'Нормально'), ('4', 'Отлично'), ('5', 'Восхитительно')], default='5', max_length=400),
        ),
        migrations.AddField(
            model_name='pool',
            name='design',
            field=models.CharField(choices=[('1', 'Отвратительно'), ('2', 'Плохо'), ('3', 'Нормально'), ('4', 'Отлично'), ('5', 'Восхитительно')], default='5', max_length=400),
        ),
        migrations.AddField(
            model_name='pool',
            name='functionality',
            field=models.CharField(choices=[('1', 'Отвратительно'), ('2', 'Плохо'), ('3', 'Нормально'), ('4', 'Отлично'), ('5', 'Восхитительно')], default='5', max_length=400),
        ),
        migrations.AddField(
            model_name='pool',
            name='other',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
    ]
