# Generated by Django 4.1.6 on 2023-05-09 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_pool_дизайн_remove_pool_другое_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
