# Generated by Django 4.1.6 on 2023-05-09 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_room_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, upload_to='C:\\Users\\MihaNik\\Desktop\\Work\\DjangoSite\\WebProgrammingWebsite\\media'),
        ),
    ]
